site_name: Documentação

nav:
  - Instruções mkdocs: "index.md"
  - Atas de Reunião:
      - Ata 1: "atas-reuniao/ata-reuniao-1.md"
  - Documento de Visão: "visao/visao.md"
  - Documento de Arquitetura: "arq/arq.md"
  - Banco de Dados:
      - Diagrama do banco de dados: "banco-de-dados/diagrama-relacionamento-inicial.md"
  - Sprint 3:
      
      - Fluxo: "sprint3/fluxo.md"
      - Permições: "sprint3/permissoes.md"
      - Endpoints: "sprint3/endpoints.md"
      - Execução Local: "sprint3/execucao-local.md"
      

theme:
  name: material