site_name: KeepUnB
site_description: Documentação oficial do projeto KeepUnB
site_author: Equipe KeepUnB

theme:
  name: material
  language: pt-BR
  logo: assets/logokeepunb.png
  favicon: assets/favicon.png

  font:
    text: DM Sans
    code: JetBrains Mono

  palette:
    scheme: default
    primary: custom
    accent: custom

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - toc.follow

nav:
  - Início: "index.md"

  - Como executar:
      - Primeiros passos: "como-executar/tutorial.md"

  - Documentação:
      - Documento de Visão: "visao/visao.md"
      - Documento de Arquitetura: "arquitetura/arq.md"
      - Comunicação, API e autenticação: "comunicacao/api-e-autenticacao.md"
      - Identidade Visual: "identidade_visual/identidade_visual.md"
      - Padronização: "padronizacao/padronizacao.md"
      - Sobre o banco de dados: "banco-de-dados/diagrama-relacionamento-inicial.md"


  - Sprints:
      - Sprint 0: "sprints/sprint0/sprint0.md"
      - Sprint 1: "sprints/sprint1/sprint1.md"
      - Sprint 2: "sprints/sprint2/sprint2.md"
      - Sprint 3: "sprints/sprint3/sprint3.md"
      - Sprint 4: "sprints/sprint4/sprint4.md"
      - Sprint 5: "sprints/sprint5/sprint5.md"
      - Sprint 6: "sprints/sprint6/sprint6.md"
      - Sprint 7: "sprints/sprint7/sprint7.md"

  - Nossa equipe:
      - Membros: "equipe/membros.md"


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css
